# Generated by Django 6.1.1 on 2026-09-28 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=50)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateField()),
                ('duracion_horas', models.PositiveIntegerField()),
                ('cantidad_estudiantes', models.PositiveIntegerField()),
                ('institucion_destino', models.CharField(max_length=200)),
                ('actividad_especifica', models.TextField(max_length=2000)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.docente')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.unidadaprendizaje')),
            ],
        ),
    ]
