# Generated by Django 6.1.1 on 2026-09-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudterreno',
            name='actividad_especifica',
        ),
        migrations.AddField(
            model_name='solicitudterreno',
            name='trabajo_a_realizar',
            field=models.TextField(default='', help_text='Descripción de las actividades y objetivos que se llevarán a cabo.', verbose_name='Trabajo / Actividad a realizar en terreno'),
            preserve_default=False,
        ),
    ]
