# Generated by Django 6.1.1 on 2026-09-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_remove_solicitudterreno_actividad_especifica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudterreno',
            name='duracion_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración en horas'),
        ),
    ]
