# Generated by Django 6.1.1 on 2026-09-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitudterreno_duracion_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudterreno',
            name='contratada',
            field=models.BooleanField(default=False, verbose_name='¿Contratada?'),
        ),
        migrations.AddField(
            model_name='solicitudterreno',
            name='realizada',
            field=models.BooleanField(default=False, verbose_name='¿Realizada?'),
        ),
    ]
