# Generated by Django 6.1.1 on 2026-09-28 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitudterreno_contratada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['codigo', 'seccion'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['nombre'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudterreno',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Terreno', 'verbose_name_plural': 'Solicitudes de Terreno'},
        ),
        migrations.AlterModelOptions(
            name='unidadaprendizaje',
            options={'ordering': ['numero', 'id'], 'verbose_name': 'Unidad de Aprendizaje', 'verbose_name_plural': 'Unidades de Aprendizaje'},
        ),
        migrations.AddField(
            model_name='solicitudterreno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='solicitudterreno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadaprendizaje',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Unidad'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='solicitudes.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='seccion',
            field=models.CharField(max_length=50, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='solicitudes.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='cantidad_estudiantes',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Estudiantes'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='solicitudes.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='duracion_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración en Horas'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='fecha_propuesta',
            field=models.DateField(verbose_name='Fecha Propuesta'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='institucion_destino',
            field=models.CharField(max_length=200, verbose_name='Lugar / Destino'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='solicitudes.unidadaprendizaje', verbose_name='Unidad de Aprendizaje'),
        ),
        migrations.AlterField(
            model_name='unidadaprendizaje',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='solicitudes.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='unidadaprendizaje',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre de la Unidad'),
        ),
        migrations.CreateModel(
            name='AprendizajeEsperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (ej: 1.1)')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='solicitudes.unidadaprendizaje', verbose_name='Unidad de Aprendizaje')),
            ],
            options={
                'verbose_name': 'Aprendizaje Esperado',
                'verbose_name_plural': 'Aprendizajes Esperados',
                'ordering': ['codigo'],
            },
        ),
    ]
