# Generated by Django 6.1.1 on 2026-09-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_asignatura_options_alter_docente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudterreno',
            name='aprendizaje_esperado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='solicitudes.aprendizajeesperado', verbose_name='Aprendizaje Esperado'),
        ),
    ]
