# Generated by Django 6.1.1 on 2026-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitudterreno_aprendizaje_esperado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudterreno',
            name='duracion_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en Horas'),
        ),
    ]
