# Generated by Django 6.1.1 on 2026-09-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_solicitudterreno_duracion_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['codigo'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='docente',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='asignaturas', to='solicitudes.docente', verbose_name='Docentes'),
        ),
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de Asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='seccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sección(es)'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='solicitudterreno',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.unidadaprendizaje', verbose_name='Unidad de Aprendizaje'),
        ),
        migrations.AlterField(
            model_name='unidadaprendizaje',
            name='nombre',
            field=models.TextField(verbose_name='Nombre / Descripción de la Unidad'),
        ),
        migrations.AlterField(
            model_name='unidadaprendizaje',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Unidad'),
        ),
    ]
