# Generated by Django 6.1.1 on 2026-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_asignatura_options_remove_asignatura_docente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['codigo', 'seccion'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='seccion',
            field=models.CharField(default='', max_length=200, verbose_name='Sección'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('codigo', 'seccion')},
        ),
    ]
